import type { Theme } from './types'

export const THEMES: Theme[] = [
  // ─── 1. 现代 Modern ─── Airbnb 风，黑白红极简
  {
    id: 'modern',
    name: '现代极简',
    description: 'Airbnb 风格，纯白底+单一品牌红',
    palette: {
      bg: '#ffffff',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #222222, #333333)',
      sectionBg: 'linear-gradient(135deg, #f7f7f7, #f0f0f0)',
      primary: '#ff385c',
      accent: '#ff385c',
      text: '#222222',
      textSub: '#717171',
      tagBg: '#ff385c',
      tagText: '#ffffff',
      priceColor: '#ff385c',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"Noto Sans SC", "Helvetica Neue", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"DIN Alternate", "Noto Sans SC", sans-serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=Noto+Sans+SC:wght@400;500;700;900',
    },
    borderRadius: { button: 8, card: 20, large: 32, pill: 50 },
    letterSpacing: { heading: -0.44, body: 0 },
    moodPrompt: '极简白底，Airbnb风格，干净留白，黑白灰+一抹红色点缀，现代摄影质感',
  },

  // ─── 2. 国潮 Guochao ─── 朱砂红+鎏金+毛笔字
  {
    id: 'guochao',
    name: '国潮风韵',
    description: '朱砂红鎏金，传统美学现代演绎',
    palette: {
      bg: '#fef8f0',
      card: '#fffbf5',
      headerBg: 'linear-gradient(135deg, #8b1a1a, #c41e3a)',
      sectionBg: 'linear-gradient(135deg, #fef0e0, #fde8d0)',
      primary: '#c41e3a',
      accent: '#b8860b',
      text: '#2d1810',
      textSub: '#8b6c5c',
      tagBg: '#c41e3a',
      tagText: '#fef0c7',
      priceColor: '#c41e3a',
      onHeader: '#fef0c7',
    },
    fonts: {
      heading: '"ZCOOL XiaoWei", "Noto Serif SC", serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Noto Serif SC", serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=ZCOOL+XiaoWei&family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;500;700',
    },
    borderRadius: { button: 4, card: 12, large: 16, pill: 50 },
    letterSpacing: { heading: 2, body: 0.5 },
    moodPrompt: '中国传统美学，朱砂红配鎏金，祥云纹样，水墨意境，国潮复古，大气磅礴',
  },

  // ─── 3. 乐游 Joyful ─── 橙黄+草绿+POP字
  {
    id: 'joyful',
    name: '乐游活力',
    description: '橙黄草绿，活泼欢快 POP 风',
    palette: {
      bg: '#fffdf5',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #ff8c00, #ffa726)',
      sectionBg: 'linear-gradient(135deg, #fff8e1, #fff3cd)',
      primary: '#ff8c00',
      accent: '#43a047',
      text: '#222222',
      textSub: '#757575',
      tagBg: '#ff8c00',
      tagText: '#ffffff',
      priceColor: '#e65100',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"ZCOOL KuaiLe", "Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Lilita One", "Noto Sans SC", sans-serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=ZCOOL+KuaiLe&family=Noto+Sans+SC:wght@400;500;700&family=Lilita+One',
    },
    borderRadius: { button: 12, card: 24, large: 32, pill: 50 },
    letterSpacing: { heading: 0, body: 0 },
    moodPrompt: '欢乐明亮，橙黄配草绿，卡通POP风格，阳光灿烂，活力四射，适合亲子出游',
  },

  // ─── 4. 自然 Nature ─── 森林绿+米白+衬线
  {
    id: 'nature',
    name: '自然清新',
    description: '森林绿米白，优雅衬线体',
    palette: {
      bg: '#f8faf5',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #2e7d32, #388e3c)',
      sectionBg: 'linear-gradient(135deg, #e8f5e9, #f1f8e9)',
      primary: '#2e7d32',
      accent: '#558b2f',
      text: '#263238',
      textSub: '#607d5b',
      tagBg: '#2e7d32',
      tagText: '#ffffff',
      priceColor: '#1b5e20',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"Noto Serif SC", serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Noto Serif SC", serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;500;700',
    },
    borderRadius: { button: 8, card: 16, large: 24, pill: 50 },
    letterSpacing: { heading: 0.5, body: 0.2 },
    moodPrompt: '自然清新，森林绿调，阳光透过树叶，清晨薄雾，鸟语花香，生态环保氛围',
  },

  // ─── 5. 美食 Foodie ─── 暖红+奶油+手写体
  {
    id: 'foodie',
    name: '美食诱惑',
    description: '暖红奶油色，手写体温馨感',
    palette: {
      bg: '#fffaf5',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #d32f2f, #e53935)',
      sectionBg: 'linear-gradient(135deg, #fff5f0, #ffecb3)',
      primary: '#d32f2f',
      accent: '#f57c00',
      text: '#3e2723',
      textSub: '#795548',
      tagBg: '#d32f2f',
      tagText: '#ffffff',
      priceColor: '#c62828',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"ZCOOL QingKe HuangYou", "Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Lilita One", "Noto Sans SC", sans-serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=ZCOOL+QingKe+HuangYou&family=Noto+Sans+SC:wght@400;500;700&family=Lilita+One',
    },
    borderRadius: { button: 12, card: 20, large: 28, pill: 50 },
    letterSpacing: { heading: -0.18, body: 0 },
    moodPrompt: '美食诱惑，暖红配奶油色，烟火气息，热腾腾的地道小吃，灯笼红光映照',
  },

  // ─── 6. 人文 Heritage ─── 深靛+古铜+宋体
  {
    id: 'heritage',
    name: '人文深蕴',
    description: '深靛古铜，宋体书卷气',
    palette: {
      bg: '#f5f5f0',
      card: '#fafaf5',
      headerBg: 'linear-gradient(135deg, #1a237e, #283593)',
      sectionBg: 'linear-gradient(135deg, #e8eaf6, #f0f0e8)',
      primary: '#1a237e',
      accent: '#8d6e63',
      text: '#212121',
      textSub: '#616161',
      tagBg: '#1a237e',
      tagText: '#ffffff',
      priceColor: '#0d47a1',
      onHeader: '#e8d5b7',
    },
    fonts: {
      heading: '"Noto Serif SC", serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Playfair Display", "Noto Serif SC", serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;500;700&family=Playfair+Display:wght@700;900',
    },
    borderRadius: { button: 4, card: 12, large: 16, pill: 50 },
    letterSpacing: { heading: 1.5, body: 0.3 },
    moodPrompt: '人文底蕴，深靛蓝配古铜色，历史古迹，水墨长卷，庄重典雅，文化之旅',
  },

  // ─── 7. 亲子 Family ─── 粉橙+奶黄+圆润POP
  {
    id: 'family',
    name: '亲子乐园',
    description: '粉橙奶黄，圆润可爱 POP',
    palette: {
      bg: '#fffbf7',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #ff7043, #ff8a65)',
      sectionBg: 'linear-gradient(135deg, #fff3e0, #fff9c4)',
      primary: '#ff7043',
      accent: '#ffb300',
      text: '#3e2723',
      textSub: '#8d6e63',
      tagBg: '#ff7043',
      tagText: '#ffffff',
      priceColor: '#e64a19',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"ZCOOL KuaiLe", "Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Lilita One", "Noto Sans SC", sans-serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=ZCOOL+KuaiLe&family=Noto+Sans+SC:wght@400;500;700&family=Lilita+One',
    },
    borderRadius: { button: 16, card: 28, large: 36, pill: 50 },
    letterSpacing: { heading: 0, body: 0 },
    moodPrompt: '温馨亲子，粉橙配奶黄，卡通元素，气球彩带，欢乐童趣，全家出游',
  },

  // ─── 8. 家庭游 Roadtrip ─── 沙漠橙+天空蓝+路线元素
  {
    id: 'roadtrip',
    name: '自驾旅途',
    description: '沙漠橙天空蓝，公路冒险感',
    palette: {
      bg: '#fafcff',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #e65100, #ff8f00)',
      sectionBg: 'linear-gradient(135deg, #e3f2fd, #fff3e0)',
      primary: '#e65100',
      accent: '#0288d1',
      text: '#263238',
      textSub: '#78909c',
      tagBg: '#e65100',
      tagText: '#ffffff',
      priceColor: '#bf360c',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Oswald", "Noto Sans SC", sans-serif',
      googleImport: 'https://cdn.jsdelivr.net/gh/nickchenyx/gfonts-mirror@main/css2?family=Noto+Sans+SC:wght@400;500;700;900&family=Oswald:wght@500;700',
    },
    borderRadius: { button: 10, card: 16, large: 24, pill: 50 },
    letterSpacing: { heading: -0.18, body: 0 },
    moodPrompt: '自驾冒险，沙漠橙配天空蓝，公路延伸远方，行李箱地图，自由旅途，家庭自驾',
  },
]

export const getTheme = (id: string): Theme =>
  THEMES.find(t => t.id === id) ?? THEMES[0]
