import type { Theme } from './types'

export const THEMES: Theme[] = [
  // ─── 1. 现代 Modern ─── Airbnb 风，黑白红极简
  {
    id: 'modern',
    name: '现代极简',
    description: 'Airbnb 风格，纯白底+单一品牌红',
    palette: {
      bg: '#ffffff',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #222222, #333333)',
      sectionBg: 'linear-gradient(135deg, #f7f7f7, #f0f0f0)',
      primary: '#ff385c',
      accent: '#ff385c',
      text: '#222222',
      textSub: '#717171',
      tagBg: '#ff385c',
      tagText: '#ffffff',
      priceColor: '#ff385c',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"Noto Sans SC", "Helvetica Neue", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"DIN Alternate", "Noto Sans SC", sans-serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=Noto+Sans+SC:wght@400;500;700;900',
    },
    borderRadius: { button: 8, card: 20, large: 32, pill: 50 },
    letterSpacing: { heading: -0.44, body: 0 },
    moodPrompt: '航拍俯瞰视角，极简构图，大面积留白，黑白摄影质感加一抹红色点缀，城市天际线与地标建筑，杂志封面级摄影，现代高级感',
  },

  // ─── 2. 国潮 Guochao ─── 朱砂红+鎏金+毛笔字
  {
    id: 'guochao',
    name: '国潮风韵',
    description: '朱砂红鎏金，传统美学现代演绎',
    palette: {
      bg: '#fef8f0',
      card: '#fffbf5',
      headerBg: 'linear-gradient(135deg, #8b1a1a, #c41e3a)',
      sectionBg: 'linear-gradient(135deg, #fef0e0, #fde8d0)',
      primary: '#c41e3a',
      accent: '#b8860b',
      text: '#2d1810',
      textSub: '#8b6c5c',
      tagBg: '#c41e3a',
      tagText: '#fef0c7',
      priceColor: '#c41e3a',
      onHeader: '#fef0c7',
    },
    fonts: {
      heading: '"ZCOOL XiaoWei", "Noto Serif SC", serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Noto Serif SC", serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=ZCOOL+XiaoWei&family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;500;700',
    },
    borderRadius: { button: 4, card: 12, large: 16, pill: 50 },
    letterSpacing: { heading: 2, body: 0.5 },
    moodPrompt: '国潮插画风格，朱砂红与鎏金配色，祥云纹样边框，水墨晕染背景，地标建筑以工笔画风格呈现，中国传统美学与现代设计融合，大气磅礴',
  },

  // ─── 3. 乐游 Joyful ─── 橙黄+草绿+POP字
  {
    id: 'joyful',
    name: '乐游活力',
    description: '橙黄草绿，活泼欢快 POP 风',
    palette: {
      bg: '#fffdf5',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #ff8c00, #ffa726)',
      sectionBg: 'linear-gradient(135deg, #fff8e1, #fff3cd)',
      primary: '#ff8c00',
      accent: '#43a047',
      text: '#222222',
      textSub: '#757575',
      tagBg: '#ff8c00',
      tagText: '#ffffff',
      priceColor: '#e65100',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"ZCOOL KuaiLe", "Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Lilita One", "Noto Sans SC", sans-serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=ZCOOL+KuaiLe&family=Noto+Sans+SC:wght@400;500;700&family=Lilita+One',
    },
    borderRadius: { button: 12, card: 24, large: 32, pill: 50 },
    letterSpacing: { heading: 0, body: 0 },
    moodPrompt: '3D卡通渲染风格，明亮橙黄色调，Q版地标建筑和可爱旅行元素，行李箱和地图散落，蓝天白云草地，活泼欢快POP海报风，适合年轻人出游',
  },

  // ─── 4. 自然 Nature ─── 森林绿+米白+衬线
  {
    id: 'nature',
    name: '自然清新',
    description: '森林绿米白，优雅衬线体',
    palette: {
      bg: '#f8faf5',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #2e7d32, #388e3c)',
      sectionBg: 'linear-gradient(135deg, #e8f5e9, #f1f8e9)',
      primary: '#2e7d32',
      accent: '#558b2f',
      text: '#263238',
      textSub: '#607d5b',
      tagBg: '#2e7d32',
      tagText: '#ffffff',
      priceColor: '#1b5e20',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"Noto Serif SC", serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Noto Serif SC", serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;500;700',
    },
    borderRadius: { button: 8, card: 16, large: 24, pill: 50 },
    letterSpacing: { heading: 0.5, body: 0.2 },
    moodPrompt: '自然风光摄影，森林绿色调，阳光穿透树冠洒下光斑，晨雾缭绕的山谷与湖泊，地标建筑隐现于自然之中，国家地理杂志风格，治愈系氛围',
  },

  // ─── 5. 美食 Foodie ─── 暖红+奶油+手写体
  {
    id: 'foodie',
    name: '美食诱惑',
    description: '暖红奶油色，手写体温馨感',
    palette: {
      bg: '#fffaf5',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #d32f2f, #e53935)',
      sectionBg: 'linear-gradient(135deg, #fff5f0, #ffecb3)',
      primary: '#d32f2f',
      accent: '#f57c00',
      text: '#3e2723',
      textSub: '#795548',
      tagBg: '#d32f2f',
      tagText: '#ffffff',
      priceColor: '#c62828',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"ZCOOL QingKe HuangYou", "Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Lilita One", "Noto Sans SC", sans-serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=ZCOOL+QingKe+HuangYou&family=Noto+Sans+SC:wght@400;500;700&family=Lilita+One',
    },
    borderRadius: { button: 12, card: 20, large: 28, pill: 50 },
    letterSpacing: { heading: -0.18, body: 0 },
    moodPrompt: '美食摄影风格，暖红与奶油色调，当地特色美食和食材环绕地标建筑，热气腾腾的烟火气，灯笼红光映照街巷，人间烟火温暖治愈',
  },

  // ─── 6. 人文 Heritage ─── 深靛+古铜+宋体
  {
    id: 'heritage',
    name: '人文深蕴',
    description: '深靛古铜，宋体书卷气',
    palette: {
      bg: '#f5f5f0',
      card: '#fafaf5',
      headerBg: 'linear-gradient(135deg, #1a237e, #283593)',
      sectionBg: 'linear-gradient(135deg, #e8eaf6, #f0f0e8)',
      primary: '#1a237e',
      accent: '#8d6e63',
      text: '#212121',
      textSub: '#616161',
      tagBg: '#1a237e',
      tagText: '#ffffff',
      priceColor: '#0d47a1',
      onHeader: '#e8d5b7',
    },
    fonts: {
      heading: '"Noto Serif SC", serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Playfair Display", "Noto Serif SC", serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=Noto+Serif+SC:wght@400;700&family=Noto+Sans+SC:wght@400;500;700&family=Playfair+Display:wght@700;900',
    },
    borderRadius: { button: 4, card: 12, large: 16, pill: 50 },
    letterSpacing: { heading: 1.5, body: 0.3 },
    moodPrompt: '纪录片电影色调，深靛蓝与古铜色，历史古迹在黄昏光线下庄重矗立，老照片质感叠加，文化符号和碑文元素，沉浸式人文旅行纪实风',
  },

  // ─── 7. 亲子 Family ─── 粉橙+奶黄+圆润POP
  {
    id: 'family',
    name: '亲子乐园',
    description: '粉橙奶黄，圆润可爱 POP',
    palette: {
      bg: '#fffbf7',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #ff7043, #ff8a65)',
      sectionBg: 'linear-gradient(135deg, #fff3e0, #fff9c4)',
      primary: '#ff7043',
      accent: '#ffb300',
      text: '#3e2723',
      textSub: '#8d6e63',
      tagBg: '#ff7043',
      tagText: '#ffffff',
      priceColor: '#e64a19',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"ZCOOL KuaiLe", "Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Lilita One", "Noto Sans SC", sans-serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=ZCOOL+KuaiLe&family=Noto+Sans+SC:wght@400;500;700&family=Lilita+One',
    },
    borderRadius: { button: 16, card: 28, large: 36, pill: 50 },
    letterSpacing: { heading: 0, body: 0 },
    moodPrompt: '温馨亲子插画风格，粉橙奶黄柔和色调，一家三口手牵手的剪影，气球彩带和棒棒糖装饰，地标建筑卡通化，圆润可爱童趣风，温暖幸福感',
  },

  // ─── 8. 家庭游 Roadtrip ─── 沙漠橙+天空蓝+路线元素
  {
    id: 'roadtrip',
    name: '自驾旅途',
    description: '沙漠橙天空蓝，公路冒险感',
    palette: {
      bg: '#fafcff',
      card: '#ffffff',
      headerBg: 'linear-gradient(135deg, #e65100, #ff8f00)',
      sectionBg: 'linear-gradient(135deg, #e3f2fd, #fff3e0)',
      primary: '#e65100',
      accent: '#0288d1',
      text: '#263238',
      textSub: '#78909c',
      tagBg: '#e65100',
      tagText: '#ffffff',
      priceColor: '#bf360c',
      onHeader: '#ffffff',
    },
    fonts: {
      heading: '"Noto Sans SC", sans-serif',
      body: '"Noto Sans SC", sans-serif',
      number: '"Oswald", "Noto Sans SC", sans-serif',
      googleImport: 'https://fonts.googleapis.cn/css2?family=Noto+Sans+SC:wght@400;500;700;900&family=Oswald:wght@500;700',
    },
    borderRadius: { button: 10, card: 16, large: 24, pill: 50 },
    letterSpacing: { heading: -0.18, body: 0 },
    moodPrompt: '公路旅行电影画面，沙漠橙与天空蓝，一条公路延伸向远方地标，SUV行驶在旷野之中，行李绑在车顶，地图和指南针元素，自由冒险感，宽银幕构图',
  },
]

export const getTheme = (id: string): Theme =>
  THEMES.find(t => t.id === id) ?? THEMES[0]
